---
# Get clusters fact

- block:
    - name: Gather vmware clusters from vCenter/ESXi
      uri:
        url: >-
          https://{{ vmware_provisioner_hostname }}/rest/vcenter/cluster
        method: GET
        headers:
          vmware-api-session-id: "{{ vmware_provisioner_session_id }}"
        status_code: 200
        return_content: yes
        validate_certs: "{{ vmware_provisioner_validate_certs }}"
      register: vmware_provisioner_clusters_result
      no_log: "{{ vmware_provisioner_no_log | bool }}"

    - name: Setup fact with vmware clusters
      set_fact:
        vmware_provisioner_clusters_fact: >-
          {{ vmware_provisioner_clusters_result.json.value }}

  when: vmware_provisioner_clusters_fact is not defined
  tags:
    - role::vmware_provisioner
    - role::vmware_provisioner::clusters
