---
# Get clusters facts

- block:
    - name: Gather vmware clusters facts from vCenter/ESXi
      vmware_cluster_info:
        datacenter: "{{ vmware_provisioner_vm_datacenter }}"
        hostname: "{{ vmware_provisioner_hostname }}"
        username: "{{ vmware_provisioner_username }}"
        password: "{{ vmware_provisioner_password }}"
        port: "{{ vmware_provisioner_port | default(omit) }}"
        validate_certs: "{{ vmware_provisioner_validate_certs }}"
      register: vmware_provisioner_clusters_facts_result

    - name: Setup fact with vmware clusters facts
      set_fact:
        vmware_provisioner_clusters_facts: >-
          {{ vmware_provisioner_clusters_facts_result.clusters }}
  when: vmware_provisioner_clusters_facts is not defined
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::facts
