---
# Get datastores facts

- block:
    - name: Gather datastores facts from vCenter/ESXi
      vmware_datastore_info:
        datacenter: "{{ vmware_provisioner_vm_datacenter }}"
        hostname: "{{ vmware_provisioner_hostname }}"
        username: "{{ vmware_provisioner_username }}"
        password: "{{ vmware_provisioner_password }}"
        port: "{{ vmware_provisioner_port | default(omit) }}"
        validate_certs: "{{ vmware_provisioner_validate_certs }}"
      register: vmware_provisioner_datastores_facts_result

    - name: Setup fact with vmware datastores facts
      set_fact:
        vmware_provisioner_datastores_facts: >-
          {{ vmware_provisioner_datastores_facts_result.datastores }}
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::datastores
