---
# Patch vmware_guest module to support multiple datastores

- block:
    - name: Locate ansible modules
      command: >-
        {{ ansible_facts.python.executable }}
        -c "{{ python_code }}"
      register: vmware_provisioner_locate_vmware_guest_result
      changed_when: no
      vars:
        python_code: >-
          from distutils.sysconfig import get_python_lib;
          print(get_python_lib())

    - name: Patch ansible vmware_guest module
      patch:
        dest: >-
          {{ vmware_provisioner_locate_vmware_guest_result.stdout
             + "/"
             + vmware_provisioner_modules_rel_dir
             + "/vmware_guest.py" }}
        src: datastore.patch
        remote_src: no
        backup: yes
        state: present
  tags:
    - role::vmware_provisioner
    - role::vmware_provisioner::patch
