---
# Get datacenters fact

- block:
    - name: Get vmware session id
      uri:
        url: >-
          https://{{ vmware_provisioner_hostname }}/rest/com/vmware/cis/session
        user: "{{ vmware_provisioner_username }}"
        password: "{{ vmware_provisioner_password }}"
        method: POST
        force_basic_auth: yes
        status_code: 200
        return_content: yes
        validate_certs: "{{ vmware_provisioner_validate_certs }}"
      register: vmware_provisioner_session_id_result
      no_log: "{{ vmware_provisioner_no_log | bool }}"

    - name: Setup fact with vmware session id
      set_fact:
        vmware_provisioner_session_id: >-
          {{ vmware_provisioner_session_id_result.json.value }}
