---
# Get current vmware vms fact

- block:
    - block:
        - name: Gather basic vmware virtual machines fact from vCenter/ESXi
          vmware_vm_info:
            hostname: "{{ vmware_provisioner_hostname }}"
            username: "{{ vmware_provisioner_username }}"
            password: "{{ vmware_provisioner_password }}"
            port: "{{ vmware_provisioner_port | default(omit) }}"
            validate_certs: "{{ vmware_provisioner_validate_certs }}"
            vm_type: all
          register: vmware_provisioner_vms_basic_fact_result

        - name: Setup fact with vmware virtual machines gathered basic fact
          set_fact:
            vmware_provisioner_vms_basic_fact: >-
              {{ vmware_provisioner_vms_basic_fact_result.virtual_machines }}
      when:
        - >-
          vmware_provisioner_gather_basic_vm_fact
          or vmware_provisioner_gather_detailed_vm_fact
        - >-
          vmware_provisioner_basic_vms_fact is not defined
          or vmware_provisioner_gather_vm_fact_force

    - block:
        - name: Gather detailed vmware virtual machines fact from vCenter/ESXi
          vmware_guest_info:
            datacenter: >-
              {{ vm.datacenter
              | default(vmware_provisioner_vm_datacenter)
              | default(omit, boolean=true) }}
            folder: >-
              {{ vm.folder
              | default(vmware_provisioner_vm_folder)
              | default(omit, boolean=true) }}
            hostname: "{{ vmware_provisioner_hostname }}"
            name: "{{ vm.name | default(vmware_provisioner_vm_name) }}"
            username: "{{ vmware_provisioner_username }}"
            password: "{{ vmware_provisioner_password }}"
            port: "{{ vmware_provisioner_port | default(omit) }}"
            uuid: >-
              {{ vm.uuid
              | default(vmware_provisioner_vm_uuid)
              | default(omit, boolean=true) }}
            validate_certs: "{{ vmware_provisioner_validate_certs }}"
          when: >-
            vm.name in vmware_provisioner_vms_basic_fact
                       | map(attribute="guest_name")
                       | list
          register: vmware_provisioner_vms_detailed_fact_result
          loop: "{{ vmware_vms_to_gather_fact }}"
          loop_control:
            loop_var: vm
            label: "{{ vm.name }}"

        - name: Setup fact with vmware virtual machines gathered detailed fact
          set_fact:
            vmware_provisioner_vms_detailed_fact: >-
              {{ vmware_provisioner_vms_detailed_fact_result.results
                 | selectattr("instance", "defined")
                 | map(attribute="instance")
                 | list }}
      when:
        - vmware_provisioner_gather_detailed_vm_fact
        - >-
          vmware_provisioner_vms_detailed_fact is not defined
          or vmware_provisioner_gather_vm_fact_force
  tags:
    - role::vmware_provisioner
    - role::vmware_provisioner::vms
